### ISSUE TITLE
ESPHome config question

### ISSUE THREAD

**Issue by Chaoscontrol** [JeffWDH/bm6-battery-monitor#6]
Sorry to open an issue, but discussions are not enabled in the repo. 

I've been checking your ESPHome code, and I don't fully understand why you choose to poll the BM6 instead of just doing a BT Proxy, which is what I thought would work. I'm trying to make it work with this code, and it did at some point, but struggling with the range. Using [this integration](https://github.com/Rafciq/BM6). 

Would polling (using your config) has any advantage vs proxy? I don't fully understand either tbh. 

```
esphome:
  name: esp32-c3--bt-proxy
  friendly_name: C3 BT Proxy

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf # IDF required for BT Proxy
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: n

# Enable logging
logger:

# Enable Home Assistant API
api:
  # For single core chips like C3, from docs
  on_client_connected:
    - esp32_ble_tracker.start_scan:
       continuous: true
  on_client_disconnected:
    - esp32_ble_tracker.stop_scan:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # power_save_mode: none Can't be used with BLE
  fast_connect: true
  output_power: 8.5db

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "C3-Test Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    active: true
    # For single core chips like C3, from docs
    continuous: false

bluetooth_proxy:
  active: true
```

Moving the ESP outside my house and close to the driveway makes the ESP lose Wifi range, and inside the house, Wifi is ok but it doesn't get into the BM6 range. 

Another question, is it possible that the BM6 only reports periodically? Even getting my phone next to the car with the app, sometimes it won't connect at all. Thinking maybe it advertises once every 15min or something like that? Could you confirm this?

Many thanks!
